# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fastball_cpp <- function(inputList, dim, numSwaps) {
    .Call(`_backbone_fastball_cpp`, inputList, dim, numSwaps)
}

