# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

scobit_loglike_cpp <- function(x1, x2, y, params) {
    .Call('_backbone_scobit_loglike_cpp', PACKAGE = 'backbone', x1, x2, y, params)
}

scobit_loglike_gr_cpp <- function(x1, x2, y, params) {
    .Call('_backbone_scobit_loglike_gr_cpp', PACKAGE = 'backbone', x1, x2, y, params)
}

